on:
  schedule:
    - cron: '13 4 * * *'

jobs:
  ensure_conversion_works:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Normal Conversion
            flags: ''
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Test the conversion works
        env:
          FLAGS: ${{ matrix.flags }}
        run: |
          composer create-project laravel/laravel myapp
          cd myapp
          composer require laravel/breeze
          php artisan breeze:install react $FLAGS
          npx laravel-breeze-chakra@latest install --force $FLAGS
